name: Main CI
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, reopened]
jobs:
  Server:
    name: Push server package to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./deployment/Dockerfile.server
          tags: ${{ secrets.SERVER_PACKAGE_IMAGE }}
          push: true
  CLI:
    name: Build CLI binary and upload S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - run: |
          CGO_ENABLED=0 GOOS=linux go build -C ./packages/cli
          bash ./deployment/aws-config.sh ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.AWS_ZONE }} && \
          bash ./deployment/accounting-cli-upload.sh ${{ secrets.CLI_S3_URL }}
  notification:
    needs: [Server, CLI]
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - run: curl https://telegram.kletskovg.tech/done/Accounting%20Published